### ISSUE TITLE
Add Ubuntu 26.04 support

### ISSUE THREAD

**Issue by enescakir** [ruby/setup-ruby#922]
GitHub recently launched Ubuntu 26.04 support in public preview.

https://github.com/actions/runner-images/issues/14226

Currently it fails with following:

> Error: The current runner (ubuntu-26.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).

**Comment by eregon** [comment]
Starting PR: https://github.com/ruby/ruby-builder/pull/29

**Comment by eregon** [comment]
I'm scheduling the builds on Ubuntu 26.04.
I plan to only build the latest patch releases, i.e. latest 3.2.x, latest 3.3.x, etc.

Only CRuby 3.2+ builds on Ubuntu 26.04:
https://github.com/ruby/ruby-builder/actions/runs/27869071846/job/82477932376
So only 3.2+ will be available.

Older versions like 3.1 & 3.0 fail to compile with:
```
compiling ./enc/euc_jp.c
In file included from ./enc/euc_jp.c:503:
enc/jis/props.kwd:146:1: error: conflicting types for ‘onig_jis_property’; have ‘const struct enc_property *(const char *, size_t)’ {aka ‘const struct enc_property *(const char *, long unsigned int)’}
enc/jis/props.kwd:40:35: note: previous declaration of ‘onig_jis_property’ with type ‘const struct enc_property *(void)’
make[1]: Leaving directory '/tmp/ruby-build.20260620105753.3822.gboL6z/ruby-3.1.7'
   40 | static const struct enc_property *onig_jis_property(/*!ANSI{*/const char *str, unsigned int len/*}!ANSI*/);
      |                                   ^~~~~~~~~~~~~~~~~
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
make[1]: *** [enc.mk:645: enc/euc_jp.o] Error 1
```

**Comment by eregon** [comment]
Done: https://github.com/ruby/setup-ruby/releases/tag/v1.314.0

**Comment by Earlopain** [comment]
> So only 3.2+ will be available.

Currently ubuntu 24 goes down to 2.0, right? (I never tried quite such an old version)

I think 3.2 is too recent a cutoff which will break many workflows. When `ubuntu-latest` becomes 26.04 (that's more common than using specific versions for the os, right? At least all the readme samples here use it) it'll break if I use a slightly older ruby.

I'll either have to stick with older os or make the os part of my matrix, both of which don't feel so great.

I understand compiling older ruby with newer compilers can be a bit of a bother, but could you consider trying to add a few more versions? The specific error you mentioned I successfully sidestepped locally like in https://github.com/rbenv/ruby-build/discussions/2529#discussioncomment-13559381 in the past.

For 2.0 on 24.04 I feel like you already had to do some twiddling to make that work. No need to go so far again, gotta stop somewhere. Where exactly, well, I can't say. Depends on how much twiddling is required I suppose.

**Comment by eregon** [comment]
> For 2.0 on 24.04 I feel like you already had to do some twiddling to make that work

I don't think I had to do anything special.
This is basically the full list of workarounds right now: https://github.com/ruby/ruby-builder/blob/5cdee7232a8b673a727ce8fceb1fd637872a208e/.github/workflows/build.yml#L80-L91
I'm on purpose not trying to workaround compilation failures, people would get it too on that OS and often they point to a deeper problem.

In general it's expected that older Rubies on newer OS don't work, and it only gets worse the further apart they are.
As a data point, macOS 26 can't even compile (correctly) anything older than 3.2 either (though on macOS we can reuse builds from older macOS runners versions so it's a smaller issue for setup-ruby).

That said, `CFLAGS="-std=gnu17"` doesn't sound so unreasonable if that alone fixes it, and feels somewhat similar to the existing `warnflags=-Wno-error=implicit-function-declaration` workaround (where Apple clang changed the default of that flag from warning to error by default).
The C toolchain kind of sucks, I feel the project should be able to declare which C standard it follows and then the compiler should use that information instead of hoping that newer C standards are compatible with older ones.

TLDR: I'll think about it, and probably try `CFLAGS="-std=gnu17"`, thank you for the link.

**Comment by Earlopain** [comment]
Tested a bit. This

```yml
    # GCC 15 defaults to gnu23
    # See https://github.com/rbenv/ruby-build/discussions/2529#discussioncomment-13559381
    - name: Set CFLAGS for Ruby <= 3.1 on ubuntu-26-04
      run: echo "CFLAGS=-std=gnu17" >> $GITHUB_ENV
      if: startsWith(matrix.os, 'ubuntu-26.04') && (startsWith(steps.ruby.outputs.ruby, 'ruby-1.9') || startsWith(steps.ruby.outputs.ruby, 'ruby-2.0') || startsWith(steps.ruby.outputs.ruby, 'ruby-2.1') || startsWith(steps.ruby.outputs.ruby, 'ruby-2.2') || startsWith(steps.ruby.outputs.ruby, 'ruby-2.3')|| startsWith(steps.ruby.outputs.ruby, 'ruby-2.4') || startsWith(steps.ruby.outputs.ruby, 'ruby-2.5')|| startsWith(steps.ruby.outputs.ruby, 'ruby-2.6')|| startsWith(steps.ruby.outputs.ruby, 'ruby-2.7')|| startsWith(steps.ruby.outputs.ruby, 'ruby-3.0')|| startsWith(steps.ruby.outputs.ruby, 'ruby-3.1'))
```

builds ruby 3.1, 3.0, 2.7, 2.5 and 2.4 but not 2.6. 2.6 fails with mjit and I didn't find a way to make that work because it ignores CFLAGS (warnflags too). You can disable mjit though

```yml
    # MJIT on Ruby 2.6 doesn't inherit CFLAGS and so warnings can't be disabled for it.
    # https://github.com/ruby/ruby/commit/1922e6ad65b7a458eeeb84da9f07724b0f1c1145
    - name: Disable MJIT for Ruby 2.6 on ubuntu-26-04
      run: echo 'RUBY_CONFIGURE_OPTS=--disable-jit-support --enable-shared --disable-install-doc' >> $GITHUB_ENV
      if: startsWith(matrix.os, 'ubuntu-26.04') && startsWith(steps.ruby.outputs.ruby, 'ruby-2.6')
```

Even earlier versions don't seem to like the newer libraries which I won't bother with.

**Comment by eregon** [comment]
The problems with that are:
* I'm not convinced overriding `CFLAGS` is OK, I think one should set cflags like [here](https://github.com/ruby/ruby/blob/1d493d90543e4304c644ab7ebb8726774768ab8d/doc/contributing/building_ruby.md#building-with-address-sanitizer) (but also there seems to be no clear docs on this) (or ruby-build `RUBY_CFLAGS`)
* That condition is really long, one idea would be to get a floating point version and check `that < 3.2`
* It's unclear to me if `-std=gnu17` is a good idea, that begs for more problems with future runners. Maybe it should be `-std=gnu99` since CRuby is C99? But then that might break some extensions which expect e.g. C11 features (atomics / thread-local). So I guess `-std=gnu17` is safer, but we need to then make this conditional on each runner because e.g. older runners' CC might not know about C17.
* Ideally the `-std=gnu17` workaround would apply to CRuby itself but not extensions, where we should not hide compatibility issues with latest gcc.
* If we do this for 26.04 will we have to do it for all future Ubuntu versions too? I'm not keen to keep using workarounds for a while. The fact it breaks now is a good reason to not support < 3.2, if we do it later it will only be harder.

**Comment by eregon** [comment]
The MJIT workaround I won't do, so the gnu17 workaround would bring 2.7, 3.0 and 3.1 and nothing else.

**Comment by eregon** [comment]
I thought more about it and I don't think we can address:
> * Ideally the `-std=gnu17` workaround would apply to CRuby itself but not extensions, where we should not hide compatibility issues with latest gcc.

Which I think a serious issue because e.g. people would use Ubuntu 26.04 in CI, and believe their project works on 26.04, and yet their extension might not work on a real Ubuntu 26.04 because of the extra flags we passed to gcc, but no extra flags for real users. Would probably be saved by newer Ruby versions in CI which don't need the workaround, but it feels brittle and wrong.

Workarounds should not have such side effects, so I'm leaning towards: Ubuntu 26.04 supports only Ruby 3.2+ because older versions fail to compile on it.

**Comment by IsaacG** [comment]
If I understand correctly, Ubuntu 26.04 can't be used until the toolcache https://github.com/ruby/ruby-builder/releases/tag/toolcache includes ubuntu-26.04 assets. It looks like there are no Ubuntu 26.04 assets there yet so Ubuntu 26.04 cannot yet be used.

**Comment by eregon** [comment]
@IsaacG No that's completely wrong. You can find it's supported by reading e.g. https://github.com/ruby/ruby-builder/#ruby-builder and https://github.com/ruby/ruby-builder/releases/tag/ruby-3.4.10
