### ISSUE TITLE
Runner cannot update rubygems

### ISSUE THREAD

**Issue by luke-hill** [ruby/setup-ruby#529]
### Ensure the following before filing this issue

- [X] I verified it reproduces with the latest version with `- uses: ruby/setup-ruby@v1` (see [Versioning policy](https://github.com/ruby/setup-ruby/blob/master/README.md#versioning))

- [X] I tried to reproduce the issue locally by following the workflow steps (including all commands done by `ruby/setup-ruby`, except for `Downloading Ruby` & `Extracting Ruby`),
and it did not reproduce locally (if it does reproduce locally, it's not a ruby/setup-ruby issue)

### Are you running on a GitHub-hosted runner or a self-hosted runner?

GitHub-hosted runner

### Link to the failed workflow job (must be a public workflow job, so the necessary information is available)

https://github.com/cucumber/cucumber-ruby-core/actions/runs/6383187734/job/17323334688?pr=265

PR code quicklink: https://github.com/cucumber/cucumber-ruby-core/pull/265/files

### Any other notes?

Possibly related to previous issue I raised #518 - The fix I was told was to update rubygems. I now get an error when I try update on ruby 2.5

```
ERROR:  Error installing rubygems-update:
  	There are no versions of rubygems-update (= 3.4.20) compatible with your Ruby & RubyGems
  	rubygems-update requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
  ERROR:  While executing gem ... (NoMethodError)
      undefined method `version' for nil:NilClass
```

**Comment by eregon** [comment]
That's clearly a bug of RubyGems or that old Ruby 2.5.
Probably `gem update --system` doesn't work on Ruby 2.5, did you try that locally?
You can probably workaround by manually passing the last RubyGems version which supports Ruby 2.5.
See https://github.com/ruby/setup-ruby/issues/441

In general I would recommend to avoid updating rubygems or bundler and just use the defaults.

**Comment by luke-hill** [comment]
Hi @eregon this contradicts the advice of @MSP-Greg who I believe is also responsible here

**Comment by eregon** [comment]
Report this to rubygems or bundler then, we are not responsible for those bugs here.
If you want to make a PR to select a better rubygems version for old Rubies like suggested in https://github.com/ruby/setup-ruby/issues/441#issuecomment-1374923260, you are welcome to do so.

**Comment by eregon** [comment]
Also yes, please check locally, I'm pretty sure you'll see the same problem.

**Comment by eregon** [comment]
To be clear, why I'm annoyed here is because you checked `it did not reproduce locally` but you didn't try.
Feel free to ask such help in discussion but not in issues, issues are only for bugs of setup-ruby itself, not of issues in Ruby/RubyGems/Bundler/gems/etc.

**Comment by luke-hill** [comment]
FYI the same problem isn't occurring locally. But I've worked around it. I've managed to hack around it to cover 2.5 until we drop it.

FYI as volunteers, please don't be immune to the fallacy you are immune from criticism. If we are commenting something doesn't work or isn't as described, advise accordingly. I manage many OSS repos (As you can see from the above), and we advise people to be clear with what they are expecting (I was), and why it wasn't working (I was). And not to expect anything on any time frame (I didn't).

I won't be responding any more here. But I find your conduct quite rude...

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/issues/441#issuecomment-1374923260 has the suggestion how to fix it, I pointed that issue in my first reply, but it seems you did not bother to try it and instead calling maintainers here "responsible". That's the part I cannot accept.

**Comment by eregon** [comment]
It seems you found a way in https://github.com/cucumber/cucumber-ruby-core/pull/265/files, that's great.
What I'm not clear is why do that PR, the description doesn't include anything useful.
I.e. if it worked without updating rubygems/bundler, why update it?

**Comment by eregon** [comment]
I think I should not have replied here, and just converted this to a discussion. The issue template is meant that such questions are not opened as issues but as discussions. I simply do not have time to help projects with ancient Rubies deal with old/unsupported RubyGems/Bundler bugs, I think anyone can understand that.
If it motivates people to drop old Rubies because of so many bugs, great from my POV.

**Comment by luke-hill** [comment]
> To be clear, why I'm annoyed here is because you checked it did not reproduce locally but you didn't try.

**Comment by eregon** [comment]
> FYI the same problem isn't occurring locally

Because you probably already updated RubyGems then, or maybe RVM did it for you.

Anyway, I apologize for my reaction, I guess I misinterpreted https://github.com/ruby/setup-ruby/issues/529#issuecomment-1744428606.
Although that comment suggests there is contradiction when there is none, I said "In general", and https://github.com/ruby/setup-ruby/issues/518 says "old rubygems is buggy, in that case".

I can't care less about Ruby 2.5 and old RubyGems bugs, that's the problem of anyone still using Ruby 2.5.

**Comment by eregon** [comment]
This is now fixed in https://github.com/ruby/setup-ruby/releases/tag/v1.165.0
